#tomcat image provided from docker.io 
FROM ubuntu:latest

LABEL maintainer="jeffitmind@gmail.com"

ARG UID
ARG GID
ARG USR

RUN groupadd -g "${GID}" "${USR}"
RUN useradd -u "${UID}" -g "${GID}" -m -s /bin/bash ${USR}
RUN apt-get update
RUN apt-get -y install sudo
RUN apt-get -y install vim
RUN apt-get -y install git
RUN sed -i 's/%sudo.*$/%sudo  ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers
RUN usermod -aG sudo ${USR}

USER ${USR}

EXPOSE _WELL_KNOWN_HTTP_PORT_
EXPOSE _WELL_KNOWN_HTTPS_PORT_

#CMD ["catalina.sh", "run"]
